oos/OosControlPanel/Controllers/AccountSettingController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using OosControlPanel.Models;
using OosProvider.Helper.BaseClasses;
using Facad.DataContract;
using System.Security.Claims;
using System.Collections.Generic;

namespace OosControlPanel.Controllers
{
    [Authorize]
    public class AccountSettingController : BaseController
    {
        #region Index
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Index(User model, string returnUrl)
        {


            if (ModelState.IsValid)
            {
                // return View("Error");


                var result = await OosProvider.Provider.BllService.LoginUser(model);
                if (result.IsSuccess == IsSuccess.Yes)
                {
                   
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {

            var userId = UserID;

            var result = await OosProvider.Provider.BllService.GetUserByGuid(userId);
            if (string.IsNullOrEmpty(result.Phone))
                result.Phone = "Missing";


            return View(result);
        }
        #endregion


        #region Change Phone
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> ChangePhone(AddPhoneNumberViewModel model, string returnUrl)
        {


            if (ModelState.IsValid)
            {



                if (model.Phone != model.ConfirmPhone)
                {
                    ModelState.AddModelError("", "Phone And Confirm Phone do not match!");
                }
                else
                {

                    var userId = User.Identity.GetUserId();

                    var result = await OosProvider.Provider.BllService.SaveUserPthone(userId, model.Phone);
                    if (result.IsSuccess == IsSuccess.Yes)
                    {

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", result.Message);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> ChangePhone()
        {
            AddPhoneNumberViewModel model = new AddPhoneNumberViewModel();


             var userId = User.Identity.GetUserId();

            var result = await OosProvider.Provider.BllService.GetUserByGuid(userId);
          
            model.Phone = result.Phone;


            return View(model);
        }
        #endregion


        #region Change Password
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (model.NewPassword != model.ConfirmPassword)
                {
                    ModelState.AddModelError("", "Password And Confirm Password do not match!");
                }
                else
                {
                    var userId = User.Identity.GetUserId();
                    var result = await OosProvider.Provider.BllService.SaveUserPassword(userId, model);
                    if (result.IsSuccess == IsSuccess.Yes)
                    {
                        AuthenticateUser(result);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", result.Message);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            ChangePasswordViewModel model = new ChangePasswordViewModel();
            return View(model);
        }
        #endregion




        #region Helper
       
        private void AuthenticateUser(User model)
        {
            var claims = new List<Claim>();

            // create *required* claims
            claims.Add(new Claim(ClaimTypes.NameIdentifier, model.Guid));
            claims.Add(new Claim(ClaimTypes.Name, model.UserEmail));

            var identity = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);



            // add to user here!
            AuthenticationManager.SignIn(new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = model.IsActive,
                ExpiresUtc = DateTime.UtcNow.AddDays(7)
            }, identity);

        }


        #endregion
    }
}

oos/OosControlPanel/Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using OosControlPanel.Models;
using OosProvider.Helper.BaseClasses;
using Facad.DataContract;

namespace OosControlPanel.Controllers
{
    [Authorize]
    public class ClientsController : BaseController
    {
        // GET: Clients
        public async Task<ActionResult> Index()
        {


            var model = new Clients();
            model.UserID = UserID;

            var result = await OosProvider.Provider.BllService.GetClientsForUser(model);


            return View(model);
        }


        #region Client Add/Edit
        public async Task<ActionResult> AddClient(int id)
        {


            var model = new Client();
            model.UserID = UserID;
            if (id > 0)
            {
                model.ClientID = id;
                model = await OosProvider.Provider.BllService.GetClientForUser(model);
            }


            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> AddClient(Client model)
        {


            if (ModelState.IsValid)
            {
                model.UserID = UserID;
                model.LogoImage = ReadFileFromRequest("LogoFile");


                model = await OosProvider.Provider.BllService.SaveClientForUser(model);
                if (model.IsSuccess == IsSuccess.Yes)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", model.Message);
                }
            }

            return View(model);
        }
        #endregion


      
    }
}

oos/OosControlPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Order System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
               
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OOS powerful tool to boost your business</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

oos/OosControlPanel/Views/Shared/_LayoutManage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Order System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="/Scripts/jquery-1.10.2.js"></script>
    <script src="/Scripts/jquery.mask.min.js"></script>
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Account", "Index", "AccountSetting")</li>
                    <li>@Html.ActionLink("My Companies", "Index", "Clients")</li>
                </ul>
                     @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div></div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OOS powerful tool to boost your business</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="~/Content/jquery-ui.css" />
    @*<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />*@
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
</body>
</html>