oos/OosControlPanel/Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using OosControlPanel.Models;
using OosProvider.Helper.BaseClasses;
using Facad.DataContract;

namespace OosControlPanel.Controllers
{
    [Authorize]
    public class ClientsController : BaseController
    {
        // GET: Clients
        public async Task<ActionResult> Index()
        {


            var model = new Clients();
            model.UserID = UserID;

            var result = await OosProvider.Provider.BllService.GetClientsForUser(model);


            return View(model);
        }


        #region Client Add/Edit
        public async Task<ActionResult> AddClient(int id)
        {


            var model = new Client();
            model.UserID = UserID;
            if (id > 0)
            {
                model.ClientID = id;
                model = await OosProvider.Provider.BllService.GetClientForUser(model);
            }


            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> AddClient(Client model)
        {


            if (ModelState.IsValid)
            {
                model.UserID = UserID;
                model.LogoImage = ReadFileFromRequest("LogoFile");


                model = await OosProvider.Provider.BllService.SaveClientForUser(model);
                if (model.IsSuccess == IsSuccess.Yes)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", model.Message);
                }
            }

            return View(model);
        }
        #endregion


      
    }
}

oos/OosControlPanel/Controllers/ShipmentController.cs
using Facad.DataContract;
using OosProvider.Helper.BaseClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OosControlPanel.Controllers
{
    [Authorize]
    public class ShipmentController : BaseController
    {
        public async Task<ActionResult> Index(int id=0)
        {


            var model = new Client();
            model.UserID = UserID;
            if (id > 0)
            {
                model.ClientID = id;
                model = await OosProvider.Provider.BllService.GetShipmentsForClient(model);

                if (model.IsSuccess == IsSuccess.No)
                {
                    ModelState.AddModelError("", model.Message);
                }

            }


            if (model.Shipments == null)
                model.Shipments = new System.Collections.Generic.List<Shipment>();



            return View(model);
        }


    
        public async Task<ActionResult> AddShipment(int clientID, int ShipmentID=0)
        {

            var model = new Client();
            model.Company = "No@Name.No";
            model.CompanyAddress = "No@Name.No";
            model.CompanyEmail = "No@Name.No";
            if (ModelState.IsValid)
            {
                model.UserID = UserID;
                model.ClientID = clientID;

                var provider = OosProvider.Provider.BllService;

                if (ShipmentID > 0)
                {
                    model = await provider.GetShipmentForClient(model, ShipmentID);
                    if (model.IsSuccess == IsSuccess.No)
                    {
                        ModelState.AddModelError("", model.Message);
                    }
                }
                else
                {
                    model.Shipment = new Shipment();
                }

                var groups = await provider.GetGroupsForClient(model);
                model.Groups = groups.Groups;
            }

            return PartialView(model);
        }


        [HttpPost]
        public async Task<ActionResult> AddShipment(Client model, int ShipmentID=0)
        {

            model.UserID = UserID;

            if (ModelState.IsValid)
            {
              
                model.Shipment.Image = ReadFileFromRequest("itmImg");

                model = await OosProvider.Provider.BllService.SaveShipmentForClient(model, ShipmentID);
                if (model.IsSuccess == IsSuccess.Yes)
                {
                    return RedirectToAction("Index", new { id = model.ClientID });
                }
                else
                {
                    ModelState.AddModelError("", model.Message);
                }
            }
            else
            {
                var groups = await OosProvider.Provider.BllService.GetGroupsForClient(model);
                model.Groups = groups.Groups;
                
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteShipment(Client model, int ShipmentID=0)
        {
        
                model.UserID = UserID;
                model = await OosProvider.Provider.BllService.DeleteShipmentForClient(model, ShipmentID);
                return RedirectToAction("Index", new { id = model.ClientID });
        }
    }
}

oos/OosControlPanel/Controllers/ShipmentGroupController.cs
using Facad.DataContract;
using OosProvider.Helper.BaseClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OosControlPanel.Controllers
{
    [Authorize]
    public class ShipmentGroupController : BaseController
    {
        // GET: ShipmentGroup
        public async Task<ActionResult> Index(int id = 0)
        {


            var model = new Client();
            model.UserID = UserID;
            if (id > 0)
            {
                model.ClientID = id;
                model = await OosProvider.Provider.BllService.GetGroupsForClient(model);

                if (model.IsSuccess == IsSuccess.No)
                {
                    ModelState.AddModelError("", model.Message);
                }

            }


            if (model.Groups == null)
                model.Groups = new Dictionary<int, string>();



            return View(model);
        }


        #region Group Add/Edit
        [HttpPost]
        public async Task<ActionResult> AddGroupPopup(string name, int id)
        {

            StringBuilder sb = new StringBuilder();
            var model = new Client();
            model.UserID = UserID;

            if (id > 0)
            {
                var provider = OosProvider.Provider.BllService;
                model.ClientID = id;
                model.GroupName = name;
                model = await provider.SaveGroupForClient(model);

                var groups = await provider.GetGroupsForClient(model);

              

                foreach (var item in groups.Groups)
                {
                    sb.AppendFormat("<option value=\"{0}\">{1}</option>", item.Key.ToString(), item.Value);
                }
            }


            return Content(sb.ToString());
        }

        public async Task<ActionResult> AddGroup(int clientID, int GroupID)
        {


            var model = new Client();
            model.Company = "No@Name.No";
            model.CompanyAddress = "No@Name.No";
            model.CompanyEmail = "No@Name.No";
            if (ModelState.IsValid)
            {
                model.UserID = UserID;
                model.ClientID = clientID;

                var provider = OosProvider.Provider.BllService;

                if (GroupID > 0)
                {
                    model.GroupID = GroupID;
                    model = await provider.GetGroupForClient(model);
                    if (model.IsSuccess == IsSuccess.No)
                    {
                        ModelState.AddModelError("", model.Message);
                    }
                }
                
            }

            return PartialView(model);



        }

       


        [HttpPost]
        public async Task<ActionResult> AddGroup(Client model, int GroupID)
        {


            if (ModelState.IsValid)
            {
                model.UserID = UserID;
                model.GroupID = GroupID;

                model = await OosProvider.Provider.BllService.SaveGroupForClient(model);
                if (model.IsSuccess == IsSuccess.Yes)
                {
                    return RedirectToAction("Index", new { id = model.ClientID });
                }
                else
                {
                    ModelState.AddModelError("", model.Message);
                }
            }

            return View(model);
        }


        [HttpPost]
        public async Task<ActionResult> DeleteGroup(Client model, int GroupID = 0)
        {

            model.UserID = UserID;
            model = await OosProvider.Provider.BllService.DeleteGroupForClient(model, GroupID);
            return RedirectToAction("Index", new { id = model.ClientID });
        }

        #endregion
    }
}

oos/OosControlPanel/Views/Clients/AddClient.cshtml
@using OosControlPanel.Properties
@model Facad.DataContract.Client
@{
    ViewBag.Title = "AddClient";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";

    <link rel="stylesheet" href="~/Scripts/js_color_picker_v2/js_color_picker_v2.css" media="screen">
    <script src="~/Scripts/js_color_picker_v2/color_functions.js"></script>
    <script type="text/javascript" src="~/Scripts/js_color_picker_v2/js_color_picker_v2.js"></script>

}

<h2><span class="ttl">Company</span></h2>
@*@using (Html.BeginForm("AddClient", "Clients", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))*@
@using (Html.BeginForm("AddClient", "Clients", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        @Html.AntiForgeryToken()
        <h4>Add Or Edit Company</h4>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.ClientID)

        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Company, new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(m => m.Company, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Company, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CompanyEmail, new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(m => m.CompanyEmail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CompanyEmail, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Company Phone", new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(m => m.CompanyPhone, new { @class = "phone form-control" })
                    @Html.ValidationMessageFor(m => m.CompanyPhone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Address", new { @class = "control-label" })
                <div>
                    @Html.TextAreaFor(m => m.CompanyAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CompanyAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Is Active", new { @class = "control-label" })
                <div>
                    @Html.CheckBoxFor(m => m.IsActive, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.Label("Delivery Note", new { @class = "control-label" })
                <div>
                    @Html.TextAreaFor(m => m.DeliveryNote, new { @class = "form-control", rows = "18" })
                    @Html.ValidationMessageFor(m => m.DeliveryNote, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <div>
                    @if (Model.ClientID > 0)
                    {
                        <br />
                        @Html.ActionLink("Shipments", "Index", "Shipment", new { id = Model.ClientID }, new { });
                        <br />
                        @Html.ActionLink("Group/Category", "Index", "ShipmentGroup", new { id = Model.ClientID }, new { });
                        <br />
                        @Html.Raw(string.Format("<a href=\"#\" onclick=\"window.open('{0}?domainid={1}', 'newwindow', 'width=1000, height=950'); return false; \">Previwe</a>", OosControlPanel.Properties.Settings.Default.FrontEndUrl, Model.ClientID.ToString()))

                    }
                </div>
            </div>
        </div>
    </div>
    <hr />
    <h4>Host Details</h4>
    <hr />
    <div class="col-md-4">
        <div class="form-group">
            @Html.HiddenFor(m => m.LogoImageID)
            @if (Model.LogoImageID > 0)
            {
                <img id="image_upload_preview" src="/blob/Index/@Model.LogoImageID.ToString()" alt="your image" />
            }
            else
            {
                <img id="image_upload_preview" src="http://placehold.it/100x100" alt="your image" />
            }
            <div class="upload">
                <input type='file' id="inputFile" name="LogoFile" />
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(m => m.Domain, new { @class = "control-label" })

            <div>
                @Html.TextBoxFor(m => m.Domain, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Preparation Time", new { @class = "control-label" })
            <div>
                @Html.TextBoxFor(m => m.PreparationTime, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Background Color", new { @class = "control-label" })
            <div class="fake-input">
                @Html.TextBoxFor(m => m.BackgroundColor, new { @class = "form-control", maxlength = "7" })
                <img style="float:right;padding-right:1px;padding-top:1px" src="/images/select_arrow.gif" onmouseover="this.src='/images/select_arrow_over.gif'" onmouseout="this.src='/images/select_arrow.gif'" onclick="showColorPicker(this,document.getElementById('BackgroundColor'))">
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Header Color", new { @class = "control-label" })
            <div class="fake-input">
                @Html.TextBoxFor(m => m.HeaderColor, new { @class = "form-control", maxlength = "7" })
                <img style="float:right;padding-right:1px;padding-top:1px" src="/images/select_arrow.gif" onmouseover="this.src='/images/select_arrow_over.gif'" onmouseout="this.src='/images/select_arrow.gif'" onclick="showColorPicker(this,document.getElementById('HeaderColor'))">
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            @Html.Label("Include Company Name", new { @class = "control -label" })
            <div>
                @Html.CheckBoxFor(m => m.IncludeCompanyName, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Include Company Email", new { @class = "control -label" })
            <div>
                @Html.CheckBoxFor(m => m.IncludeCompanyEmail, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Include Company Phone", new { @class = "control -label" })
            <div>
                @Html.CheckBoxFor(m => m.IncludeCompanyPhone, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
        </div>
    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                            @Html.ActionLink("Cancel", "Index", new { id = 0 }, new { @class = "btn btn-default" })
                        </div>
                    </div>
}

oos/OosControlPanel/Views/Clients/Company.cshtml
@model Facad.DataContract.Client

@{
    ViewBag.Title = "Company";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";

    <link rel="stylesheet" href="~/Scripts/js_color_picker_v2/js_color_picker_v2.css" media="screen">
    <script src="~/Scripts/js_color_picker_v2/color_functions.js"></script>
    <script type="text/javascript" src="~/Scripts/js_color_picker_v2/js_color_picker_v2.js"></script>
}

<h2>My Campaign</h2>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<hr />

    @using (Html.BeginForm("Company", "Clients", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
  
   
    <div id="Shipments">
        @{ 
            var Shipments = Model.Shipments;
            foreach (var item in Shipments)
            {
        <table id="item" class="defTbl">
            <tr>
                <td rowspan="3" class="col-md-2">
                    <img id="image_upload_previewShipment" class="image_upload_preview" src="http://placehold.it/100x100" alt="your image" />
                    <div class="upload">
                        <input type='file' id="inputFileShipment" onchange="readItemsURL(this, 'image_upload_previewShipment')" />
                    </div>
                </td>

                <td class="col-md-1">
                    @Html.Label("Name", new { @class = "control-label" })
                </td>
                <td colspan="3" class="col-md-7">
                    <div>
                        @Html.TextBox("itemName", item.Name, new { @class = "itemLong", maxlength ="300" })
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Description", new { @class = "control-label" })
                </td>
                <td colspan="3">
                    <div>
                        @Html.TextArea("itemDescription", item.Description, new { @class = "itemArr", maxlength ="500" })
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Measure", new { @class = "control-label" })
                </td>
                <td>
                    <div>
                        @Html.TextBox("itemUofM", item.UofM, new { @class = "itemShort", maxlength ="12" })
                    </div>
                </td>

                <td>
                    @Html.Label("Price", new { @class = "control-label" })
                </td>
                <td>
                    <div>
                        @Html.TextBox("itemPrice", item.Price, new { @class = "itemShort", maxlength = "12" })
                    </div>
                </td>
                <td>
                    <div>
                        <a href="javascript:void(0)" onclick="openConfirmDialog(function () { removeShipment(event) })">Delete</a>
                    </div>
                </td>

            </tr>
        </table>
                }
            }

    </div>

    <table  class="defTbl">
        <tr>
            <td><a class="btn btn-default" href="javascript:void(0)" onclick="addShipment()">Add Shipment</a></td>
            <td><input type="submit" class="btn btn-default" value="Save" /></td>
        </tr>
    </table>
       


            }

oos/OosControlPanel/Views/Clients/Index.cshtml
@model Facad.DataContract.Clients
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<h2><span class="ttl">My Companies</span></h2>
<div class="row">
    <h4>Add Or Edit Company</h4>
    <hr />
    <table class="defTbl">
        <tr class="trTblHead">
            <th>IsActive</th>
            <th>Company</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Domain</th>
            <th></th>
        </tr>

        @{
            var cc = Model.UserClients;
            foreach (var item in cc)
            {
                <tr>
                    <td>@(item.IsActive ? "Yes" : "No")</td>
                    <td>@Html.Label(item.Company, "Company", new { id = item.ClientID })</td>
                    <td>@Html.Label(item.CompanyEmail, new { @class = "control-label" })</td>
                    <td>@Html.Label(item.CompanyPhone, new { @class = "control-label" })</td>
                    <td>@Html.Label(item.Domain, new { @class = "control-label" })</td>
                    <td>@Html.ActionLink("Edit", "AddClient", new { id = item.ClientID })</td>
                </tr>
            }
        }


        <tr class="cmdTr">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>@Html.ActionLink("Add Company", "AddClient", new { id = 0 })</td>
        </tr>
    </table>
    </div>